--- #YAML:1.0
name:               Weather-NOAA-Alert
version:            0.90
abstract:           Polling and parsing of NOAA CAP 1.1 Alerts
author:
    - Michael Stovenour <michael@stovenour.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  0
    LWP::Simple:   0
    Test::More:    0
    XML::Twig:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
